name: DashAPI
version: "${project.version}"
main: com.lichenaut.dashapi.DashAPI
api-version: 1.21
author: lichenaut
description: Adds "dash()" -> set the velocity of entities in terms of blocks instead of a vector.
